config/routes.rb
Planner::Application.routes.draw do
  resources :providers

  resources :activities

  resources :days

  resources :segments

  resources :plans

  resources :preferences

  resources :profiles

  resources :users
  
  resource :session
  
  resource :wizard

  

  
  root 'wizards#index'
  get '/step_two' => "wizards#step_two", :as => "step_two"
  get '/step_three' => "wizards#step_three", :as => "step_three"

  get '/signin' => "sessions#new" , :as => "signin"
  get '/login' => "sessions#create", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
   
  get '/customize' => "plans#customize", :as => "customize" 
  post '/save_plan' => "plans#save_for_user", :as => "save_plan" 

  get '/add_stay' => "plans#add_stay", :as => "add_stay"
  get '/delete_stay' => "plans#delete_stay", :as => "delete_stay"
  get '/add_transport' => "plans#add_transport", :as => "add_transport"
  get '/delete_transport' => "plans#delete_transport", :as => "delete_transport"  
  
  get '/add_day' => "plans#add_day", :as => "add_day"
  get '/delete_day' => "plans#delete_day", :as => "delete_day"
   
  get '/daybyday' => "segments#daybyday", :as => "daybyday"
  get '/summary' => "segments#summary", :as => "summary"
  get '/choose' => "segments#choose", :as => "choose"
  post '/swap' => "segments#swap", :as => "swap"
  
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  belongs_to :plan
  has_many :days, -> { order('order_in_segment') }
  has_and_belongs_to_many :providers

  def is_stay?
    self.segment_type == 'Stay'
  end

end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy, :daybyday, :summary]
  before_action :signed_in_user, only: [:choose]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # GET /daybyday
  def daybyday
    respond_to do |format|
      format.js {}
      format.json { }
    end
  end

  # GET /summary
  def summary
    respond_to do |format|
      format.js {}
      format.json { }
    end
  end
  
  # GET /choose
  def choose
  @segments = Segment.select{ |segment| segment.orig_segment_id.nil? && segment.is_stay?}
    respond_to do |format|
      format.html # choose.html.erb
    end
  end

  # GET /swap
  def swap
    if params[:commit] == 'Skip'
      redirect_to plan_url(params[:plan_id]) 
    else
      Plan.swap(params[:plan_id], params[:orig_segment_id], params[:new_segment_id])
      respond_to do |format|
        format.html { redirect_to plan_url(params[:plan_id]) }
      end
    end
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @segment }
      else
        format.html { render action: 'new' }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:segment_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:name, :description, :thumbnail, :segment_type, :plan_id)
    end
    
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<%= form_for(@segment) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_area :thumbnail %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br>
    <%= f.number_field :plan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/segments/choose.html.erb
<br/>
<%= form_tag swap_path do %>

    <% @segments.each do |segment| %>
    
		<div class="segment_choose">
			
			<div class="segment_radio">
				<%= radio_button_tag 'new_segment_id', segment.id %>
			</div>
			<div class="segment_selection">
				<%= image_tag(segment.thumbnail, :class => "segment_img") %>	
				<div class="segment_desc"> 
					<div class="segment_title"> <%= segment.name %> </div> 
					<br/> <br/>
					<div class="segment_text"> <%= segment.description %> </div> 
				</div>
			</div> 

		</div>    

        <br/>

    <% end %>
    <%= hidden_field_tag "plan_id", params[:plan_id] %> 
    <%= hidden_field_tag "orig_segment_id", params[:segment_id] %> 
	<div class="segment_choose_buttons">
		<%= submit_tag 'Go', :class => 'segment_button' %>
		<%= submit_tag 'Skip', :class => 'segment_button' %>
	</div>

<% end %>		
</br>

app/views/segments/daybyday.js.erb
$('.segment_text:eq(<%= (@segment.order_in_plan - 1) %>)').replaceWith(
	'<div class="segment_text">' 
		<% i = 1 %>    
		<% @segment.get_days.each do |day| %>
			+ 'Day <%= i %> - <%= day.name %> <br/>'
			<% i += 1 %>	
		<% end %> 
	+ '</div>'
)
$('.segment_show:eq(<%= (@segment.order_in_plan - 1) %>)').replaceWith(
	'<%= link_to "Summary", summary_url(:segment_id => @segment.id), :class => "segment_show", :remote => :true %>'
)

app/views/segments/edit.html.erb
<h1>Editing segment</h1>

<%= render 'form' %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/index.html.erb
	<br/>

    <% @segments.each do |segment| %>
    
		<div class="segment" draggable = "true">
			<%= image_tag(segment.thumbnail, :class => "segment_img") %>	
			<div class="segment_desc"> 
				<div class="segment_title"> <%= segment.name %> </div> 
				<br/> <br/>
				<div class="segment_text"> <%= segment.description %> </div> 
			</div> 
			<%= link_to 'Day by Day', daybyday_url(:id => segment.id), :class => "segment_show", :remote => :true %>		
		</div>    

        <br/>

    <% end %>

app/views/segments/new.html.erb
<h1>New segment</h1>

<%= render 'form' %>

<%= link_to 'Back', segments_path %>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @segment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @segment.description %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @segment.thumbnail %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @segment.plan_id %>
</p>

<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>

app/views/segments/show.js.erb
$('.segment_text:eq(<%= (@segment.id - 1) %>)').replaceWith(
	'<div class="segment_text">'    
		<% @segment.days.each do |day| %>
			+ '<%= day.name %> <br/>'	
		<% end %> 
	+ '</div>'
)

app/views/segments/summary.js.erb
$('.segment_text:eq(<%= (@segment.order_in_plan - 1) %>)').replaceWith(
	'<div class="segment_text">' + '<%= @segment.get_description %> <br/>'	+ '</div>'
)
$('.segment_show:eq(<%= (@segment.order_in_plan - 1) %>)').replaceWith(
	'<%= link_to "Day by Day", daybyday_url(:segment_id => @segment.id), :class => "segment_show", :remote => :true %>'
)