config/routes.rb
Planner::Application.routes.draw do
  resources :providers

  resources :activities

  resources :days

  resources :segments

  resources :plans

  resources :preferences

  resources :profiles

  resources :users
  
  resource :session
  
  resource :wizard

  

  
  root 'wizards#index'
  get '/step_two' => "wizards#step_two", :as => "step_two"
  get '/step_three' => "wizards#step_three", :as => "step_three"

  get '/signin' => "sessions#new" , :as => "signin"
  get '/login' => "sessions#create", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
   
  get '/customize' => "plans#customize", :as => "customize" 
  post '/save_plan' => "plans#save_for_user", :as => "save_plan" 

  get '/add_stay' => "plans#add_stay", :as => "add_stay"
  get '/delete_stay' => "plans#delete_stay", :as => "delete_stay"
  get '/add_transport' => "plans#add_transport", :as => "add_transport"
  get '/delete_transport' => "plans#delete_transport", :as => "delete_transport"  
  
  get '/add_day' => "plans#add_day", :as => "add_day"
  get '/delete_day' => "plans#delete_day", :as => "delete_day"
   
  get '/daybyday' => "segments#daybyday", :as => "daybyday"
  get '/summary' => "segments#summary", :as => "summary"
  get '/choose' => "segments#choose", :as => "choose"
  post '/swap' => "segments#swap", :as => "swap"
  
end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :segment
  has_many :activities, -> { order('start_time') }
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:day, :segment_id)
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :segment_id %><br>
    <%= f.number_field :segment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Segment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.day %></td>
        <td><%= day.segment_id %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @day.day %>
</p>

<p>
  <strong>Segment:</strong>
  <%= @day.segment_id %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>