config/routes.rb
Planner::Application.routes.draw do
  resources :providers

  resources :activities

  resources :days

  resources :segments

  resources :plans

  resources :preferences

  resources :profiles

  resources :users
  
  resource :session
  
  resource :wizard

  

  
  root 'wizards#index'
  get '/step_two' => "wizards#step_two", :as => "step_two"
  get '/step_three' => "wizards#step_three", :as => "step_three"

  get '/signin' => "sessions#new" , :as => "signin"
  get '/login' => "sessions#create", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
   
  get '/customize' => "plans#customize", :as => "customize" 
  post '/save_plan' => "plans#save_for_user", :as => "save_plan" 

  get '/add_stay' => "plans#add_stay", :as => "add_stay"
  get '/delete_stay' => "plans#delete_stay", :as => "delete_stay"
  get '/add_transport' => "plans#add_transport", :as => "add_transport"
  get '/delete_transport' => "plans#delete_transport", :as => "delete_transport"  
  
  get '/add_day' => "plans#add_day", :as => "add_day"
  get '/delete_day' => "plans#delete_day", :as => "delete_day"
   
  get '/daybyday' => "segments#daybyday", :as => "daybyday"
  get '/summary' => "segments#summary", :as => "summary"
  get '/choose' => "segments#choose", :as => "choose"
  post '/swap' => "segments#swap", :as => "swap"
  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  has_many :segments, -> { order('order_in_plan') }
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage/
                                
  # Default thumbnail images for plan and segments
  DEFAULT_PLAN_IMAGE = "travel3.gif"
  DEFAULT_SEGMENT_IMAGE = "travel4.gif"
  DEFAULT_STAY_IMAGE = "travel4.gif"
  DEFAULT_TRANSPORT_IMAGE = "flight.gif"
  
  #
  # Swap a segment in a plan with a different one
  #
  def self.swap(plan_id, segment_id, new_segment_id)
    # find original record of the segment and make a copy  
    new_segment = Segment.new
    old_segment = Segment.find(segment_id)
    new_segment.orig_segment_id = new_segment_id
    new_segment.order_in_plan = old_segment.order_in_plan
    new_segment.save
    plan = Plan.find(plan_id)
    # insert new segment and remove the old one
    plan.segments << new_segment
    plan.segments.destroy(segment_id)
  end
  
  #
  # Copy plan into into user's account
  #
  def self.save_plan(plan_id, user_id)
    old_plan = Plan.find(plan_id)
    orig_plan = Plan.find(old_plan.orig_plan_id)
    new_plan = orig_plan.dup
#    new_plan = Plan.new
#    new_plan.orig_plan_id = old_plan.orig_plan_id
    new_plan.user_id = user_id
    new_plan.save
    # iterate over segments to duplicate them
    old_plan.segments.each do |segment| 
      orig_segment = Segment.find(segment.orig_segment_id)
      new_segment = orig_segment.dup
#      new_segment = Segment.new
#      new_segment.orig_segment_id = segment.orig_segment_id
#      new_segment.order_in_plan = segment.order_in_plan
      new_segment.save
      new_plan.segments << new_segment
    end
  end

  #
  # Add segment data
  #
  def add_segments(segments)
 
    if segments
      segment_order = 1
      
      # iterate over segments list
      segments.each do |k, v|
        new_segment = Segment.new
        new_segment.order_in_plan = segment_order
        segment_order += 1
        logger.info "adding segment name: " + v["title"] + " adding description: " + v["description"]
        # set segment attributes
        new_segment.name = v["title"]
        new_segment.description = v["description"]
        new_segment.thumbnail = v["thumbnail"]
        new_segment.segment_type = v["segment_type"]
        new_segment.save
        
        # process days list if any
        if v["days"]
          day_order = 1
          days = v["days"]
          # iterate over the list of days
          days.each do |d_k, d_v|
            new_day = Day.new
            new_day.order_in_segment = day_order
            day_order += 1
            logger.info " --  adding day name: " + d_v
            # set day attributes
            new_day.name = d_v
            new_day.save
            new_segment.days << new_day
          end
        end
        
        # put segment into plan
        self.segments << new_segment
        
      end # segments.each
    end # if segments
  end # def

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :store_location, only: [:show, :new]
  before_action :signed_in_user, only: [:customize, :new]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
    @plan.name = 'New Plan'
    @plan.description ='Plan Description' 
    @plan.user_id = current_user.id
  end

  # GET /plans/1/edit
  def edit
  end
  
  # POST /plans
  # POST /plans.json
  def create
    if params[:commit] == 'Skip'
      redirect_to root_url 
    else  
      @plan = Plan.new(plan_params)
      # make the plan belong to the current user
      @plan.user_id = current_user.id
  
      respond_to do |format|
        if @plan.save
          @plan.add_segments(params['segments'])
          format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
          format.json { render action: 'show', status: :created, location: @plan }
        else
          format.html { render action: 'new' }
          format.json { render json: @plan.errors, status: :unprocessable_entity }
        end
      end
     end  
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
  
  # Save plan into my account
  def customize
      logger.info "--- in customize ----"
      redirect_back_or plans_path, 'Now please save the plan into your account'
  end
  
  
  # Save plan into my account
  def save_for_user
      logger.info "--- in save_for_user ----"
      Plan.save_plan(session[:recommended_plan_id], current_user.id)
      session.delete(:recommended_plan_id)
      redirect_to plans_path, :notice => "Plan saved in your account"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :description, :plan_type, :thumbnail, :avatar, :orig_plan_id, :user_id)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
  
  # recommend a plan based on the user
  def recommend (user_id)
    # currently returns a hard-coded plan
    recommended_plan_id = 1
    
    session[:recommended_plan_id] = recommended_plan_id
    return Plan.find(recommended_plan_id)
  end
  
end

app/views/plans/_form.html.erb
<br/>
<div class="new_plan_section">
<br/>

<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
      <% @plan.errors.full_messages.each do |msg| %>
        <% flash.now[:alert] = msg %>
      <% end %>
  <% end %>
  
  	<% seg_count = 0 %>
	<div class="new_plan_header">
  	
  		<div class="title_section">
  			<%= f.label :name, "Plan Title", :class => 'title_tag' %>
			<%= f.text_field :name, :class => 'title_field' %>
  		</div>

  		<div class="description_section">
  			<%= f.label :description, "Description", :class => 'description_tag' %>
			<%= f.text_area :description, :class => 'description_field' %>
  		</div>
  		
  		<div class="type_section">
  			<%= f.label :plan_type, "Plan Type", :class => 'type_tag' %>
  			<%= f.select :plan_type, options_for_select([ "Family with Kids", "Couple Only", "History and Museum Buffs", "Adventure Backpackers" ], "Family with Kids"), {}, :class => 'type_field' %> 
  		</div>

		<%= image_tag @plan.avatar.url(:thumb), :class => 'plan_thumbnail' %>

		<div class="file-input-wrapper">
	  		<%= button_tag "Replace", :class=>"btn-file-input" %>
	 		<%= f.file_field :avatar, :class => 'change_plan_thumbnail'  %>
		</div>

  	</div>
  	
  	<% @plan.segments.each_with_index do |segment, i| %>
  		<% segment_with_index = "segment["+i.to_s+"]" %>	
	  	<% if segment.is_stay? %>
		 	<div class="add_stay_section" segment_id="<%=i.to_s%>"> 
		 		<div class="segment_header">
					<div class="segment_title_section"> 
						<%= label_tag :name, "Stay Title", :class => "title_tag" %> 
						<%= text_field_tag segment_with_index+"[title]", segment.name, :class => "title_field" %> 
					</div> 
					<div class="segment_description_section"> \
						<%= label_tag :description, "Description", :class => "description_tag" %> \
						<textarea name=<%=segment_with_index+"[description]"%> class="description_field"><%= segment.description %></textarea>
					</div>
					<div class="segment_location_section"> 
						<%= label_tag :city, "Town or City", :class => "city_tag" %> 
						<%= text_field_tag segment_with_index+"[city]", segment.city, :class =>"city_field" %> 
						<%= label_tag :country, "Country", :class => "country_tag" %> 
						<%= country_select segment_with_index, "country", [segment.country], {}, {:class=>"country_field"} %>
					</div>
					<%= image_tag segment.thumbnail, :class => "segment_thumbnail" %>
					<%= hidden_field_tag segment_with_index+"[thumbnail]", segment.thumbnail %> 
					<%= hidden_field_tag segment_with_index+"[segment_type]", segment.segment_type %> 
					<%= link_to "Change", "#", :class => "change_segment_thumbnail" %> 
	  				<%= link_to "X", delete_stay_url(:segment_id=>i.to_s), :class => "delete_segment", :remote => true %> 
  				</div>
  				
  				<% segment.days.each_with_index do |day, j| %>
					<div day_id="<%=j.to_s%>" segment_id="<%=i.to_s%>" class="day_section"> 
						<%= label_tag :name, "Day's Activities", :class => "day_description_tag" %> 
						<textarea name=<%="segments["+i.to_s+"][days]["+j.to_s+"]"%> class="day_description_field"><%= day.name %></textarea> 
						<%= link_to "X", delete_day_url(:day_id=>j.to_s, :segment_id=>i.to_s), :class => "delete_day", :remote => true %> 
					</div> 
  				<% end %>
				<div class="new_day_placeholder" segment_id="<%=i.to_s%>"></div> 
				<div class="add_day_section">	
					<%= link_to "Add Day", add_day_url(:day_id=>segment.days.length.to_s, :segment_id=>i.to_s), :segment_id=>i.to_s, :class => "add_day", :remote => :true %>
				</div> 
			</div> 
		<% else %>
			<div class="add_transport_section" segment_id="<%=i.to_s%>"> 
				<div class="segment_title_section"> 
					<%= label_tag :name, "From and To", :class => "title_tag" %> 
					<%= text_field_tag segment_with_index+"[title]", segment.name, :class => "title_field" %> 
				</div> 
				<div class="segment_description_section"> 
					<%= label_tag :description, "Description", :class => "description_tag" %> 
					<textarea name=<%=segment_with_index+"[description]"%> class="description_field"><%= segment.description %></textarea> 
				</div> 
				<div class="segment_location_section"> 
					<%= label_tag :segment_type, "Type", :class => "type_tag" %> 
					<%= select_tag segment_with_index+"[segment_type]", options_for_select([ "Air", "Train", "Bus", "Ship", "Other" ], segment.segment_type), :class => "type_field" %> 
				</div> 
				<%= image_tag segment.thumbnail, :class => "segment_thumbnail" %>
				<%= hidden_field_tag segment_with_index+"[thumbnail]", segment.thumbnail %> 
				<%= link_to "Change", "/", :class => "change_segment_thumbnail" %> 
  				<%= link_to "X", delete_transport_url(:segment_id=>i.to_s), :class => "delete_segment", :remote => true %> 
			</div>
	  	<% end %>
  	<% end %>
  	    
    
	<div class="new_segment_placeholder"></div>
	
	<div class="add_segment_links">
	  	<%= link_to "Add Stay", add_stay_url(:segment_id=>1), :class => "add_stay", :remote => true %>
  		<%= link_to "Add Transportation", add_transport_url(:segment_id=>1), :class => "add_transport", :remote => true %>
  	</div>
  	  	
	<div class="actions">
    	<%= f.submit 'Save', :class => "save_plan_button" %>
    	<%= f.submit 'Skip', :class => "save_plan_button" %>
  	</div>
  	
<% end %>

<br/>
</div>

app/views/plans/add_day.js.erb
<%# Replace Add Day link with a placeholder so can't cause duplicate day ids by fast clicking %>
$('.add_day[segment_id=<%= params[:segment_id]%>]').replaceWith('\
  	<%= link_to "", "#", :segment_id=>params[:segment_id], :class => "add_day" %> \
')
h = $('.add_stay_section[segment_id=<%= params[:segment_id]%>]').height();
$('.add_stay_section[segment_id=<%= params[:segment_id]%>]').height(h+75);
$('.new_day_placeholder[segment_id=<%= params[:segment_id]%>]').replaceWith('\
		<div day_id=<%=params[:day_id]%> segment_id=<%=params[:segment_id]%> class="day_section"> \
			<%= label_tag :name, "Day's Activities", :class => "day_description_tag" %> \
			<textarea name=<%="segments["+params[:segment_id].to_s+"][days]["+params[:day_id].to_s+"]"%> class="day_description_field"></textarea> \
			<%= link_to "X", delete_day_url(:day_id=>params[:day_id], :segment_id=>params[:segment_id]), :class => "delete_day", :remote => true %> \
		</div> \
		<div class="new_day_placeholder" segment_id="<%=params[:segment_id]%>"></div> \
')
<%# Now update Add Day link %>
$('.add_day[segment_id=<%= params[:segment_id]%>]').replaceWith('\
  	<%= link_to "Add Day", add_day_url(:day_id=>params[:day_id].to_i+1, :segment_id=>params[:segment_id]), :segment_id=>params[:segment_id], :class => "add_day", :remote => :true %> \
')

app/views/plans/add_stay.js.erb
$('.add_stay').replaceWith('\
  	<%= link_to "Add Stay", add_stay_url(:segment_id=>params[:segment_id].to_i+1), :class => "add_stay", :remote => true %> \
')
$('.add_transport').replaceWith('\
  	<%= link_to "Add Transportation", add_transport_url(:segment_id=>params[:segment_id].to_i+1), :class => "add_transport", :remote => true %> \
')
$('.new_segment_placeholder').replaceWith('\
	<div class="add_stay_section" segment_id=<%=params[:segment_id]%>> \
		<div class="segment_header"> \
			<div class="segment_title_section"> \
				<%= label_tag :name, "Stay Title", :class => "title_tag" %> \
				<%= text_field_tag "segments["+params[:segment_id].to_s+"][title]", "", :class => "title_field" %> \
			</div> \
			<div class="segment_description_section"> \
				<%= label_tag :description, "Description", :class => "description_tag" %> \
				<textarea name=<%="segments["+params[:segment_id].to_s+"][description]"%> class="description_field"></textarea> \
			</div> \
			<div class="segment_location_section"> \
				<%= label_tag :city, "Town or City", :class => "city_tag" %> \
				<%= text_field_tag "segments["+params[:segment_id].to_s+"][city]", "", :class =>"city_field" %> \
				<%= label_tag :country, "Country", :class => "country_tag" %> \
				<%=j country_select "segments["+params[:segment_id].to_s+"]", "country", ["Italy", "France", "Germany", "United Kingdom", "Switzerland", "Ireland", "Austria"], {}, {:class=>"country_field"} %> \
			</div> \
			<%= image_tag Plan::DEFAULT_STAY_IMAGE, :class => "segment_thumbnail" %> \
			<%= hidden_field_tag "segments["+params[:segment_id].to_s+"][thumbnail]", Plan::DEFAULT_STAY_IMAGE %> \
			<%= hidden_field_tag "segments["+params[:segment_id].to_s+"][segment_type]", "Stay" %> \
			<%= link_to "Change", "/", :class => "change_segment_thumbnail" %> \
	  		<%= link_to "X", delete_stay_url(:segment_id=>params[:segment_id]), :class => "delete_segment", :remote => true %> \
  		</div> \
		<div class="new_day_placeholder" segment_id="<%=params[:segment_id]%>"></div> \
   		<div class="add_day_section"> \
	  		<%= link_to "Add Day", add_day_url(:day_id=>1, :segment_id=>params[:segment_id]), :segment_id=>params[:segment_id], :class => "add_day", :remote => :true %> \
  		</div> \
	</div> \
	<div class="new_segment_placeholder"></div> \
')

app/views/plans/add_transport.js.erb
$('.add_stay').replaceWith('\
  	<%= link_to "Add Stay", add_stay_url(:segment_id=>params[:segment_id].to_i+1), :class => "add_stay", :remote => true %> \
')
$('.add_transport').replaceWith('\
  	<%= link_to "Add Transportation", add_transport_url(:segment_id=>params[:segment_id].to_i+1), :class => "add_transport", :remote => true %> \
')
$('.new_segment_placeholder').replaceWith('\
	<div class="add_transport_section" segment_id=<%=params[:segment_id]%>> \
		<div class="segment_title_section"> \
			<%= label_tag :name, "From and To", :class => "title_tag" %> \
			<%= text_field_tag "segments["+params[:segment_id].to_s+"][title]", "", :class => "title_field" %> \
		</div> \
		<div class="segment_description_section"> \
			<%= label_tag :description, "Description", :class => "description_tag" %> \
			<textarea name=<%="segments["+params[:segment_id].to_s+"][description]"%> class="description_field"></textarea> \
		</div> \
		<div class="segment_location_section"> \
			<%= label_tag :segment_type, "Type", :class => "type_tag" %> \
			<%=j select_tag "segments["+params[:segment_id].to_s+"][segment_type]", options_for_select([ "Air", "Train", "Bus", "Ship", "Other" ], "Air"), :class => "type_field" %> \
		</div> \
		<%= image_tag Plan::DEFAULT_TRANSPORT_IMAGE, :class => "segment_thumbnail" %> \
		<%= hidden_field_tag "segments["+params[:segment_id].to_s+"][thumbnail]", Plan::DEFAULT_TRANSPORT_IMAGE %> \
		<%= link_to "Change", "/", :class => "change_segment_thumbnail" %> \
  		<%= link_to "X", delete_transport_url(:segment_id=>params[:segment_id]), :class => "delete_segment", :remote => true %> \
	</div> \
	<div class="new_segment_placeholder"></div> \
')

app/views/plans/delete_day.js.erb
$('.day_section[day_id=<%= params[:day_id]%>][segment_id=<%= params[:segment_id]%>]').remove()
h = $('.add_stay_section[segment_id=<%= params[:segment_id]%>]').height();
$('.add_stay_section[segment_id=<%= params[:segment_id]%>]').height(h-75);

app/views/plans/delete_stay.js.erb
$('.add_stay_section[segment_id=<%= params[:segment_id]%>]').remove()

app/views/plans/delete_transport.js.erb
$('.add_transport_section[segment_id=<%= params[:segment_id]%>]').remove()

app/views/plans/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
	<br/>

	<div class="plan_heading"> 
		<div class="plan_heading_title"> Your Plans: </div>	
	</div>

	<br/>

    <% current_user.plans.each do |plan| %>
    
 		<div class="plan">   

			<div class="plan_desc"> 
				<div class="plan_title"> <%= plan.name %> </div> 
				<br/> <br/>
				<div class="plan_text"> <%= plan.description %> </div> 
			</div> 
			<div class="plan_pictures"> 
				<% plan.segments.select{|s| s.is_stay?}.each_with_index do |segment,index| %>
					<%= image_tag(segment.thumbnail, :class => "plan_img") %>
					<% break if index == 4 %>
				<% end %>
 			</div> 
        	<%= link_to 'Show', plan, :class => "plan_show" %>
     		<%= link_to 'Edit', edit_plan_path(plan), :class => "plan_edit"%>
        	<%= link_to 'Delete', plan, method: :delete, data: { confirm: 'Are you sure?' }, :class => "plan_destroy" %>
        	
   		</div>    

        <br/>

    <% end %>

app/views/plans/new.html.erb
<%= render 'form' %>

app/views/plans/show.html.erb
	<br/>

	<div class="plan_heading"> 
		<div class="plan_heading_title"> Your Plan: <%= @plan.name %> </div>
		<div class="plan_heading_description"> <%= @plan.description %> </div>
		<% if signed_in? %>
			<% if @plan.user_id.nil? %>
				<%= link_to 'Save in my Account', save_plan_path, :method => "post", :class => "plan_heading_actions" %>
			<% end %>
		<% else%>
				<%= link_to 'Customize', customize_path, :class => "plan_heading_actions" %>
		<% end %>	
	</div>
	
	<br/>

    <% @plan.segments.each do |segment| %>
    	<% if segment.is_stay?
    		style_suffix, daybyday_txt = "_stay", 'Day by Day' 
    	  else
    		style_suffix, daybyday_txt = "_transport",''
    	  end
    	%>

		<div class=<%= "segment"+style_suffix %> draggable = "true">
			<%= image_tag(segment.thumbnail, :class => "segment_img"+style_suffix) %>	
			<div class=<%= "segment_desc"+style_suffix %>> 
				<div class="segment_title"> <%= segment.name %> </div> 
				<br/> <br/>
				<div class="segment_text"> <%= segment.description %> </div> 
			</div> 
			<% if signed_in? %>
				<%= link_to 'Swap', choose_url(:segment_id => segment.id, :plan_id => @plan.id), :class => "segment_swap" %>		
			<% end %>	
			<%= link_to daybyday_txt, daybyday_url(:segment_id => segment.id), :class => "segment_show", :remote => :true %>
		</div>    

        <br/>

    <% end %>