config/routes.rb
Planner::Application.routes.draw do
  resources :providers

  resources :activities

  resources :days

  resources :segments

  resources :plans

  resources :preferences

  resources :profiles

  resources :users
  
  resource :session
  
  resource :wizard

  

  
  root 'wizards#index'
  get '/step_two' => "wizards#step_two", :as => "step_two"
  get '/step_three' => "wizards#step_three", :as => "step_three"

  get '/signin' => "sessions#new" , :as => "signin"
  get '/login' => "sessions#create", :as => "login"
  delete '/logout' => "sessions#destroy", :as => "logout"
   
  get '/customize' => "plans#customize", :as => "customize" 
  post '/save_plan' => "plans#save_for_user", :as => "save_plan" 

  get '/add_stay' => "plans#add_stay", :as => "add_stay"
  get '/delete_stay' => "plans#delete_stay", :as => "delete_stay"
  get '/add_transport' => "plans#add_transport", :as => "add_transport"
  get '/delete_transport' => "plans#delete_transport", :as => "delete_transport"  
  
  get '/add_day' => "plans#add_day", :as => "add_day"
  get '/delete_day' => "plans#delete_day", :as => "delete_day"
   
  get '/daybyday' => "segments#daybyday", :as => "daybyday"
  get '/summary' => "segments#summary", :as => "summary"
  get '/choose' => "segments#choose", :as => "choose"
  post '/swap' => "segments#swap", :as => "swap"
  
end

app/views/layouts/_footer.html.erb
<div class="bigbox_footer">

	<div class="footer">
		<ul id="footer_menu">
			<li><a href="/">iPhone</a></li>
			<li><a href="/">About</a></li>
			<li><a href="/">Help</a></li>
			<li><a href="/">Contact</a></li>
			<li><a href="/">Terms & Privacy</a></li>
		</ul>
		(c) Plan Mine Too Inc.
	</div>

</div>

app/views/layouts/_header.html.erb
<div class="bigbox_header">

	<div class="logo"><a href="/"><img class="logo_img" src="/images/planminetoo_logo.jpg"></img></a></div>
	
	<div class="access">
		<ul id="access_menu">
			<% if signed_in? %>
				<% if current_user.profile.first_name %>
					<li>Welcome <%= current_user.profile.first_name %>! </li>
				<% else %>
					<li>Welcome <%= current_user.name %>!</li>
				<% end %>
				<li> <%= link_to 'Sign Out', logout_path,  method: "delete" %></li>
			<% else %>
				<% if (controller != 'sessions') && (request.path != login_path) %>
					<li><%= link_to 'Login', new_session_path %></li> 
					<li><%= link_to 'Register', new_user_path %> </li>
				<% end %>
			<% end %>
			<li><a href="/">How it Works</a></li>
			<li><%= link_to 'Share your Trip!', new_plan_path, :id => "access_button" %></li>
		</ul>
	</div>
	
	<div class="notification">				
	    <% flash.each do |key, value| %>
    	    <div class="flash_<%= key %>"><%= value %></div>
	    <% end %>
	</div>
	
	<div class="navigation">
		<ul id="navigation_menu">
			<% if signed_in? %>
			<li><a class="navigation_item" href="/">Home</a></li>
			<li><a class="navigation_item" href="/plans">Plans</a></li>
			<li><a class="navigation_item" href="/">Network</a></li>
			<li><a class="navigation_item" href="/">Ideas</a></li>
			<li><a class="navigation_item" href="/profiles/<%= current_user.profile.id %>">Account</a></li>
			<% end %>
		</ul>	
	</div>
	
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plan Mine Too</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="bigbox_body">
		<%= yield %>
	</div>

	<%= render 'layouts/footer' %>

</body>
</html>